### ISSUE TITLE
ABN

### ISSUE THREAD

**Issue by jiangzhengkai** [visinf/da-sac#4]
Thanks for your interesting work! Have you done experiments without ABN, i.e, training souce data with fixed BN and updating BN for the second stage?

**Comment by arnike** [comment]
Hi Jiang,

this is an interesting point! We have not tried this scenario, though. I think the gain attained by training with augmentation consistency to some extent scales with the inital model accuracy, so how accurate the model is at the start of the second stage is important. If you want to experiment with finetuning BN of the second stage (as opposed to freezing it), take a look at this paper: [https://arxiv.org/pdf/2101.08482.pdf](https://arxiv.org/pdf/2101.08482.pdf). We have not experimented with it yet, but I believe it can push the accuracy of the framework further.

Best,
Nikita
